### ISSUE TITLE
long_description_content_type not set for Markdown

### ISSUE THREAD

**Issue by LucidOne** [zsimic/setupmeta#1]
If `long_description` is generated from README.md then
`long_description_content_type="text/markdown"` should be set

**Comment by zsimic** [comment]
Thank you very much for the report!
Fixed here: https://github.com/zsimic/setupmeta/commit/c01e9379d9de16a812fae75ea12b842c17905011

Travis deployment to pypi seems to not work currently, so I couldn't publish this new version, will publish as soon as possible.

**Comment by zsimic** [comment]
Published setupmeta v1.6.1, with this suggested addition https://pypi.org/project/setupmeta/
Thanks again!
