### ISSUE TITLE
[QUESTION] {pre-/post}-install step with setupmeta?

### ISSUE THREAD

**Issue by ruohoruotsi** [zsimic/setupmeta#20]
Thanks for the great library, it has been working so well for easy PyPI deploys! 

**Question:** I have a binary dependency (an NLP machine learned model) that I'd like to {pre-/post}-install via a bash script. With setuptools I'd invoke it via the scheme below with `cmdclass={'install': ...`. Is there a good way to accomplish an extra install step via setupmeta? or what do you recommend to support installing a binary dependency to `./bin/`. Thank you and Cheers!

```
import atexit
from setuptools.command.install import install

def _post_install():
    print('POST INSTALL')

class new_install(install):
    def __init__(self, *args, **kwargs):
        super(new_install, self).__init__(*args, **kwargs)
        atexit.register(_post_install)

setuptools.setup(
    cmdclass={'install': new_install},
``` 
(from this [StackOverflow](https://stackoverflow.com/questions/20288711/post-install-script-with-python-setuptools) thread)

**Comment by zsimic** [comment]
You can apply this same technique with setupmeta (in general, setupmeta only auto-fills missing stuff, doesn't prevent you from explicitly specifying anything).

There is not great way I know off to pull in external (non-python) dependencies. I tend to specify those in the README file, and let users bring it themselves (like via `apt` or `brew` on OSX etc).

Writing such a post-install in a multi-platform way is probably going to be challenging :)

**Comment by ruohoruotsi** [comment]
Thanks Zoran!!
