### ISSUE TITLE
Incorrect version since v2.5.3 release

### ISSUE THREAD

**Issue by 00willo** [zsimic/setupmeta#27]
Results of testing recent versions of setupmeta with

```
python setup.py --version
```

2.5.3 - shows correct version –  as  1.0.11+hlocal.gb4894aa.dirty
2.5.4 - shows incorrect – 0.0.0
2.6.0 - shows incorrect – 0.0.0
2.6.1 - shows incorrect – 0.0.0

Options part of `setup.cfg`
```
[options]
versioning=build-id
python_requires = >=3.6
zip_safe = True
include_package_data = True
 packages = find:
package_dir =
     =src
install_requires =
    atpublic
setup_requires =
    setupmeta
tests_require =
    pytest
    pytest-spec
    pytest-cov
```

**Comment by 00willo** [comment]
Also just tested with `python setup.py version` with these results

```
$ pip install setupmeta==2.6.1
Collecting setupmeta==2.6.1
  Using cached https://files.pythonhosted.org/packages/57/11/d83a21577d265d3409a4b2f59a908cfcd6924f85e978b9e1184079fdfeb3/setupmeta-2.6.1-py2.py3-none-any.whl
Installing collected packages: setupmeta
  Found existing installation: setupmeta 2.5.3
    Uninstalling setupmeta-2.5.3:
      Successfully uninstalled setupmeta-2.5.3
Successfully installed setupmeta-2.6.1
You are using pip version 19.0.3, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

$ python setup.py version
running version

$ pip install setupmeta==2.5.3
Collecting setupmeta==2.5.3
  Using cached https://files.pythonhosted.org/packages/2b/51/b83a26c60feab8232c2fe0ad51e19f2a206eb36c0c90cac5a14ef4309c63/setupmeta-2.5.3-py2.py3-none-any.whl
Installing collected packages: setupmeta
  Found existing installation: setupmeta 2.6.1
    Uninstalling setupmeta-2.6.1:
      Successfully uninstalled setupmeta-2.6.1
Successfully installed setupmeta-2.5.3
You are using pip version 19.0.3, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

$ python setup.py version
running version
1.1.2+hlocal.g1ae6816
```

**Comment by zsimic** [comment]
Can you send me a link to that project by any chance?

It seems that you're using `setup.cfg` instead of `setup.py`, I must admit I'm not familiar with that approach, but I'll gladly add a test case and make sure it's properly handled.

Version 2.5.4 does indeed intentionally disable `setupmeta` if it's not explicitly requested by a `setup_requires=["setupmeta"]`. It seems that here it thinks it's not explicitly required, doesn't realize it is via `setup.cfg`.

**Comment by zsimic** [comment]
I think I found why: I don't think you can specify `setup_requires` in `setup.cfg`, as per this code: https://github.com/pypa/setuptools/blob/master/setuptools/__init__.py#L132-L135 (that's probably also why you have to `pip install setupmeta`).

I tried with a project where I define stuff in `setup.cfg` instead of `setup.py`, and indeed it appears as if `setup_requires` was not set at all.

I'd recommend moving your `setup_requires` to `setup.py`... as per this doc: https://docs.python.org/3/distutils/configfile.html, `setup.cfg` is meant for like optional/default stuff. I don't think you want `setupmeta` to be like optional, right?

**Comment by 00willo** [comment]
Hey, thanks for maintaining your project and the prompt reply to the issue. We have been using it for the last year across several packages, it very much helps keep things DRY across the repos.  Unfortunately, they're private repos, so we aren't able to share any direct link.

I don't read from the distutils link that using setup.cfg is for optional things only, but default sure. I can't recall if this is where we first saw it, but the pre-commit's [setup.cfg](https://github.com/pre-commit/pre-commit/blob/master/setup.cfg) looks almost identical to ours. We really like the fact that the setup.py then only needs to contain the following 2 lines

```
from setuptools import setup
setup()
```

We really like that everything is then defined as declarative metadata.  So, it definitely works and has worked well, without explicitly needed the `setupmeta` package to be installed separately.  Sorry, I now realised it may have come across like we were installing `setupmeta` manually based on my earlier comment. In that output, I was just merely showing the package versions installed as part of the testing on debugging the issue.

**Comment by zsimic** [comment]
Would you mind changing your `setup.py` to be like this then?
```
from setuptools import setup
setup(setup_requires="setupmeta")
```

That would still keep it to a minimum, and allow for the new safe-check that activates setupmeta only if it has been explicitly required (unfortunately, the stuff in `setup.cfg` is "too late" in a sense -> the hook was already called when it gets sourced apparently).

If you change your `setup.py` as above, then you can remove these lines from your `setup.cfg`:
```
setup_requires =
    setupmeta
```

Also, the following lines can go away from your `setup.cfg` when you use `setupmeta` (as it auto-fills them correctly already):
```
packages = find:
package_dir =
     =src
```

You can further simplify your `setup.cfg` by removing the 2 sections `install_requires` and `tests_require`, if:
- you have a `requirements.txt`, and a `tests/requirements.txt`
- and you're OK with this auto-fill strategy: https://github.com/zsimic/setupmeta/blob/master/docs/requirements.rst

**Comment by zsimic** [comment]
I'm all for minimal repetition BTW, via `setup.py`, or `setup.cfg` or what-have-you :)
I'm also using setupmeta mostly to reduce boilerplate in the dozens of internal projects we have.

Try my suggestion re adding a few more chars to your `setup.py`, but removing even more from `setup.cfg`, then take a look at `python setup.py explain` to confirm that the outcome is as you expect.

Let me know if that doesn't work out, I can see to better support the `.cfg` approach (we currently don't use `setup.cfg` at all... one less file to have around)

**Comment by 00willo** [comment]
Went with adding the setup_requires to the setup.py.  That worked for us. Thanks.
