### ISSUE TITLE
PyPI rejects added classifier ("Classifier: License :: OSI Approved :: GNU General Public License (GPLv3)")

### ISSUE THREAD

**Issue by blueyed** [zsimic/setupmeta#37]
Using the following `setup.py` I get an error:

```
HTTPError: 400 Client Error: Invalid value for classifiers. Error: 'License :: OSI Approved :: GNU General Public License (GPLv3)' is not a valid choice for this field for url: https://upload.pypi.org/legacy/
```

```python
from setuptools import setup

setup(
    name="pytest-enhancements",
    setup_requires="setupmeta",
    versioning="devcommit",
    maintainer="Daniel Hahler",
    url="https://github.com/blueyed/pytest-enhancements",
    author="Daniel Hahler",
    py_modules=["pytest_enhancements"],
    package_dir={"": "src"},
    description="Improvements for pytest (rejected upstream)",
    keywords="pytest plugin enhancements",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Environment :: Console",
        "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
        "Programming Language :: Python :: 2",
        "Programming Language :: Python :: 2.7",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.5",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Intended Audience :: Developers",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: Implementation :: CPython",
        "Programming Language :: Python :: Implementation :: PyPy",
        "Topic :: Utilities",
    ],
    entry_points={"pytest11": ["pytest-enhancements = pytest_enhancements"]},
    extra_requires={"testing": ["pytest"]},
)
```

`./src/pytest_enhancements.egg-info/PKG-INFO` contains:
```
Classifier: Development Status :: 4 - Beta
Classifier: Environment :: Console
Classifier: Intended Audience :: Developers
Classifier: License :: OSI Approved :: GNU General Public License (GPLv3)
Classifier: License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)
Classifier: Operating System :: OS Independent
Classifier: Programming Language :: Python :: 2
Classifier: Programming Language :: Python :: 2.7
Classifier: Programming Language :: Python :: 3
Classifier: Programming Language :: Python :: 3.5
Classifier: Programming Language :: Python :: 3.6
Classifier: Programming Language :: Python :: 3.7
Classifier: Programming Language :: Python :: 3.8
Classifier: Programming Language :: Python :: Implementation :: CPython
Classifier: Programming Language :: Python :: Implementation :: PyPy
Classifier: Topic :: Utilities
```

This appears to happen via https://github.com/zsimic/setupmeta/blob/2d5699e57b6807e44a55f5c458830b317558f0e9/setupmeta/model.py#L803-L812.

There appears to be no way to skip this, is there?

I think setupmeta should not add classifiers for the licence if there is one already.

**Comment by blueyed** [comment]
Example deploy job on Travis: https://travis-ci.com/blueyed/pytest-enhancements/jobs/247761377

**Comment by zsimic** [comment]
Oh, I wonder what's causing it, with `python setup.py explain` you can see that the auto-fill is this:
```
    license: (auto-fill) GPLv3
```

So, the value `GPLv3` is not legit? We can totally change it in `auto_fill_license()` yes.

In the meantime, you can state it explicitly in your `setup.py`, add a line for example:
```
  license="GPL",
```
and you should be good to go.

**Comment by zsimic** [comment]
But actually I think the error you see there is not from setupmeta, note that it says:
```
Invalid value for classifiers. 
Error: 'License :: OSI Approved :: GNU General Public License (GPLv3)' 
is not a valid choice for this field
```

So I think it's complaining about line 17 in your `setup.py`, it seems to not like that particular classifier.

**Comment by zsimic** [comment]
The full list of classifiers seems to be here: https://pypi.org/classifiers/
Looks like all you need is a `v3 ` before the `(`.

If the auto-filled `license` is wrong, please let me know yes, I'd love to make it right.

IIUC, the `license` field is simply shown on pypi (but no hyperlink, so I'm guessing it's free form?).
I've noticed that the serious projects seem to be simply having a short form like `MIT` or `Apache 2.0`, so I tried to emulate that with the auto-fill there.

**Comment by blueyed** [comment]
I have "GNU General Public License v3 or later (GPLv3+)" in setup.py, which is in the list of qualifiers, but setupmeta also adds 'License :: OSI Approved :: GNU General Public License (GPLv3)' then.

AFAICS ./src/pytest_enhancements.egg-info/PKG-INFO is generated via setupmeta - note that it has two classifiers.

IIRC I had an explicit "license" keyword argument for setup, but it gets overwritten from the auto-filling apparently.

**Comment by zsimic** [comment]
Aahh oops! That breaks the philosophy of never touching what was explicitly given, didn't realize that!

I'm removing this funky classifier partial auto-complete pronto, thanks for pointing this out! Didn't get it the first time.

**Comment by zsimic** [comment]
All right, version `2.6.8` should fix this nonsense now: won't sneakily add anything to `classifiers' anymore.

Sorry about that, that was a mistake to try and "inject" a classifier, totally goes agains the philosophy of "no explicit settings are changed" (and that is why I initially thought it wasn't changing your classifiers, didn't realize it actually did).

`rm -rf .eggs` should get you the latest setupmeta on next `setup.py` usage.

BTW, I noticed (there was a warning...) that you have a typo in your `setup.py`: you should do `extras_require=...` instead of `extra_requires=...` (they put the `s` in a weird place for this one)

**Comment by blueyed** [comment]
Thanks for the fix, worked: https://travis-ci.com/blueyed/pytest-enhancements/jobs/250930050.

> BTW, I noticed (there was a warning...) that you have a typo in your `setup.py`: you should do `extras_require=...` instead of `extra_requires=...` (they put the `s` in a weird place for this one)

Thanks, often get this wrong.. :/
(fixed also)

**Comment by pawanmishra0532** [comment]
Invalid value for classifiers. Error: Classifiers ['a', 'c', 'e', 'f', 'i', 'l', 'r', 's'] are not valid classifiers.
???

**Comment by zsimic** [comment]
@pawanmishra0532 how did you get that error?
`setupmeta` should only be involved in `classifiers` if you chose to state them in a file called `classifiers.txt`

Do you happen to have an unrelated such file maybe in your project?

**Comment by zsimic** [comment]
This made me realize that an unrelated `classifiers.txt` can indeed induce confusion via setupmeta, removing support for it: https://github.com/codrsquad/setupmeta/pull/69
