### ISSUE TITLE
Specify minimum git verison requirement in docs

### ISSUE THREAD

**Issue by 00willo** [zsimic/setupmeta#38]
Just noting here for those that might come looking with a similar problem.

If you're using CentOS 7, the git version in the distro yum repos is not sufficient for the default `git describe` command used here. There's also no error that there's an issue. As an example, with using `build-id` versioning with a repo that contains a `v0.5.0` tag for instance, you end up with the following using the distro supplied git version `1.8.3.1`

```
$ python setup.py explain
...
                   version:    (git       ) 0.0.59+h13049.gc75e9a9
                   versioning: (explicit  ) build-id
...
```
however, after updating to a newer version of git, say `2.16.5` from the IUS repo

```
$ python setup.py explain
...
                   version:    (git       ) 0.5.23+h13049.gc75e9a9
                   versioning: (explicit  ) build-id
...
```
Could the docs be updated to include the minimum git version contains the switches used.

**Comment by zsimic** [comment]
Thank you for reporting this!

I wonder if there's a way to detect that `git describe` didn't quite work, and issue a WARNING if so, to give a heads up that something may be fishy with version computation.

**Comment by blueyed** [comment]
Likely due to 6b7ddd9.
Note that you can use `GIT_DESCRIBE_COMMAND` to override the command being used.

I agree that there should be a) an error, and b) the default should fall back to not using `--first-parent` then (if not explicitly provided via env var).

**Comment by blueyed** [comment]
According to https://github.com/pypa/setuptools_scm/pull/346#issue-298965639 it was added in 1.8.4, so you almost have it.. ;)   (just for reference)

**Comment by zsimic** [comment]
`setupmeta` was missing reporting that `git describe` exited with code != 0, I've made it a warning now, sone gets a proper heads up.

If for any reason `git describe` now exits with code != 0, you should get some useful output, I tried by adding `--foo` to the invoked command and get this:

```
~/github/setupmeta: ./setup.py explain
/Users/zsimic/github/setupmeta/setupmeta/__init__.py:200: UserWarning: git describe --dirty --foo --tags --long --match *.* --first-parent exited with error code 129
error: unknown option `foo'
usage: git describe [<options>] [<commit-ish>...]
   or: git describe [<options>] --dirty

    --contains            find the tag that comes after the commit
...
```

**Comment by zsimic** [comment]
All right, so setupmeta `2.6.11` will have this warning, and I added this mention in `README.rst`:

```
Note: setupmeta's versioning is based on:

git describe --dirty --tags --long --match *.* --first-parent

you will need git version >= 1.8.4 if you wish to use setupmeta's versioning capabilities.
```

**Comment by blueyed** [comment]
Great.  The readme could mention the env variable maybe.

**Comment by zsimic** [comment]
I've updated https://github.com/zsimic/setupmeta/blob/master/docs/versioning.rst as well, and mentioned env var `GIT_DESCRIBE_COMMAND` there.

**Comment by blueyed** [comment]
Thanks!
