### ISSUE TITLE
Successfully installed 0.0.0

### ISSUE THREAD

**Issue by jpic** [zsimic/setupmeta#5]
Hello !

Thanks a heap for making setupmeta open source, it's my favorite new software :joy:

So, it works well except when it installs, for example:

```
$ python setup.py sdist
running sdist
running egg_info
writing processcontroller.egg-info/PKG-INFO
writing dependency_links to processcontroller.egg-info/dependency_links.txt
writing top-level names to processcontroller.egg-info/top_level.txt
reading manifest file 'processcontroller.egg-info/SOURCES.txt'
writing manifest file 'processcontroller.egg-info/SOURCES.txt'
running check
creating processcontroller-1.5.0
creating processcontroller-1.5.0/processcontroller
creating processcontroller-1.5.0/processcontroller.egg-info
copying files to processcontroller-1.5.0...
copying README.rst -> processcontroller-1.5.0
copying setup.py -> processcontroller-1.5.0
copying processcontroller/__init__.py -> processcontroller-1.5.0/processcontroller
copying processcontroller.egg-info/PKG-INFO -> processcontroller-1.5.0/processcontroller.egg-info
copying processcontroller.egg-info/SOURCES.txt -> processcontroller-1.5.0/processcontroller.egg-info
copying processcontroller.egg-info/dependency_links.txt -> processcontroller-1.5.0/processcontroller.egg-info
copying processcontroller.egg-info/top_level.txt -> processcontroller-1.5.0/processcontroller.egg-info
Writing processcontroller-1.5.0/setup.cfg
Creating tar archive
removing 'processcontroller-1.5.0' (and everything under it)
```

But then it always installs 0.0.0:

```
$ pip install -U processcontroller-1.5.0.tar.gz
Processing ./processcontroller-1.5.0.tar.gz
Building wheels for collected packages: processcontroller
  Running setup.py bdist_wheel for processcontroller ... done
  Stored in directory: /home/jpic/.cache/pip/wheels/b8/86/74/78957d4871c5feec8a32f27112a1f04d130213dbacc0f6e3d3
Successfully built processcontroller
Installing collected packages: processcontroller
  Found existing installation: processcontroller 0.0.0
    Uninstalling processcontroller-0.0.0:
      Successfully uninstalled processcontroller-0.0.0
Successfully installed processcontroller-0.0.0
```

Is this the expected behavior ?

Source code : https://yourlabs.org/processcontroller

**Comment by zsimic** [comment]
I can't reproduce this.
In your output, there seems to be an issue with determining version (hence 0.0.0), usually due to no tag being present (in git).

I just checked out your project and tried, I get correct version, and proper sdist (ie, I get `dist/processcontroller-1.5.0.tar.gz`)

**Comment by zsimic** [comment]
I think I found why. Running with `pip install -v`, I see this:

```
Running setup.py (path:.../setup.py) egg_info for package from .../processcontroller-1.5.0.tar.gz
.../.eggs/setupmeta-2.2.1-py3.6.egg/setupmeta/__init__.py:39: UserWarning: project not under a supported SCM
```

Basically, the tarball gets unpacked to a temp dir by `pip install`, and then `python setup.py egg_info` is ran there.
However, since that temp dir is not a git checkout, there is no git tag, hence version defaults to 0.0.0

I'll run this in the debugger and see what I can do.

**Comment by jpic** [comment]
Yes, that's what I think too.

The problem is the aggressive requirement version check by pip, ie.:

```

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (clilabs 0.0.0 (/usr/lib/python3.6/site-packages), Requirement.parse('clilabs>=1.1'), {'mrs'}
```

Any workaround please ?

Note that I'm not requesting to change setupmeta, just trying to figure what I'm doing wrong, how do you deal with this issue on your own packages ?

Thanks

**Comment by jpic** [comment]
That's the [only solution i found](https://yourlabs.io/oss/python-container/blob/master/bin/pypi-release#L7):

```
    sed -i "s/versioning='.*',/version='$(python setup.py version | tail -n1)',/" setup.py
```

Works for me ;)

**Comment by zsimic** [comment]
It should work now without any workaround, thanks so much for reporting this! 😃 

setupmeta 2.2.2 should now find the version properly from PKG-INFO file if present (and no .git folder), which is what happens when you pip install from source tarball.

Let me know if it doesn't work for you. I tried it with processcontroller-1.5.0.tar.gz -> works great with setupmeta v2.2.2 for me now.

**Comment by jpic** [comment]
Hello Zoran !

Thank you so much for your research, patches and comments !

Keep up the great work !
