### ISSUE TITLE
Generate MANIFEST.in ?

### ISSUE THREAD

**Issue by jpic** [zsimic/setupmeta#6]
Hello Zoran !

So, I'm living a dream with setupmeta, except sometimes installing the dist package does not define my entry points. I figured it works a lot better by adding the ini file to MANIFEST.in hopefully :joy: BUT, sometimes I forget about it ^^

Let's demonstrate:

```
$ pip install yash==0.6.1
Collecting yash==0.6.1
Collecting pyyaml (from yash==0.6.1)
Collecting cli2 (from yash==0.6.1)
Collecting colorama (from cli2->yash==0.6.1)
  Using cached https://files.pythonhosted.org/packages/4f/a6/728666f39bfff1719fc94c481890b2106837da9318031f71a8424b662e12/colorama-0.4.1-py2.py3-none-any.whl
Installing collected packages: pyyaml, colorama, cli2, yash
Successfully installed cli2-0.5.2 colorama-0.4.1 pyyaml-3.13 yash-0.6.1

$ ls test/bin/ | grep yash
```

Nothing in bin :'(

Let's try from source:

```
$ pip install -e ~/src/yash
Obtaining file:///home/jpic/src/yash
Requirement already satisfied: pyyaml in ./test/lib/python3.7/site-packages (from yash==0.6.2.dev6) (3.13)
Requirement already satisfied: cli2 in ./test/lib/python3.7/site-packages (from yash==0.6.2.dev6) (0.5.2)
Requirement already satisfied: colorama in ./test/lib/python3.7/site-packages (from cli2->yash==0.6.2.dev6) (0.4.1)
Installing collected packages: yash
  Found existing installation: yash 0.6.1
    Uninstalling yash-0.6.1:
      Successfully uninstalled yash-0.6.1
  Running setup.py develop for yash
Successfully installed yash

$ ls test/bin/ | grep yash
yash
```

Ok so hopefully the dev version has it fixed, just after I added ini files to MANIFEST.in, but i'm not 100% sure it's related: it just looks like it so far.

```
$ pip install yash==0.6.2.dev6
Collecting yash==0.6.2.dev6
  Downloading https://files.pythonhosted.org/packages/2c/1f/0bcda86d598f32504dc980e613248fb728ae94f369e213e203fed79790ea/yash-0.6.2.dev6.tar.gz
  Requested yash==0.6.2.dev6 from https://files.pythonhosted.org/packages/2c/1f/0bcda86d598f32504dc980e613248fb728ae94f369e213e203fed79790ea/yash-0.6.2.dev6.tar.gz#sha256=583890bd9b7caf30ac601ae5bec0a3b3309fc06bdd0f9dac0f74cc05a1065e8c, but installing version 0.6.2
Requirement already satisfied: pyyaml in ./test/lib/python3.7/site-packages (from yash==0.6.2.dev6) (3.13)
Requirement already satisfied: cli2 in ./test/lib/python3.7/site-packages (from yash==0.6.2.dev6) (0.5.2)
Requirement already satisfied: colorama in ./test/lib/python3.7/site-packages (from cli2->yash==0.6.2.dev6) (0.4.1)
Building wheels for collected packages: yash
  Building wheel for yash (setup.py) ... done
  Stored in directory: /home/jpic/.cache/pip/wheels/8e/3a/1e/ab14cfb2073af96b3303079a3596d3ca4c91e0f468a79166ce
Successfully built yash
Installing collected packages: yash
Successfully installed yash-0.6.2

$ ls test/bin/ | grep yash
yash
```

Do you think we should automate "adding files used by setupmeta to MANIFEST.in" ?

Thanks in advance for sharing some of your insight !

Have a great day ;)

**Comment by zsimic** [comment]
Thank you! It does come in handy for avoiding a bunch of boilerplate doesn't it :)

I took a quick look, and I couldn't tell why 0.6.1 doesn't properly include your entry point.
TBH, I haven't delved much into `MANIFET.in` yet, usually I don't use one, and when I do I haven't had to include `*.txt` or anything like that.

I'll try and pinpoint what causes the packaged tarball to miss on those entry points like that.
The `entry_points.ini` is just one way of expressing them, it shouldn't matter how you express them (either inline in `setup.py` or via `entry_points.ini`) -> they should end up in the package dist-info as `entry_point.txt` (generated by setuptools, not setupmeta)

**Comment by zsimic** [comment]
I found the issue!
Somehow I never ran into this, my guess is that you are publishing in a different way than I do :)

So, the issue is that when the source dist tarball is unpacked, it doesn't necessarily have all of the files from your source repo. Most of the info however should already be in the `PKG-INFO` and `*.egg-info` folder that are part of that sdist tarball. `setupmeta` however wasn't looking hard enough at those packaged folders.

I've corrected that now, looking at `PKG-INFO` extensively, and extracting as much info from it as possible. Version 2.3.2 has that correction, please try again.

With latest 2.3.2, you shouldn't need to bundle those files (`entry_point.ini` for example) in `MANIFEST.in` (you may bundle anything you like, but entry-points determination will work correctly whether you do or not)

Thank you very much for reporting this! 
Looking at `PKG-INFO` extensively when it is there (meaning we are in a packaged sdist) was the right thing to do, I just missed it before.

I've added tests to cover this case (maintaining 100% test coverage :) )

**Comment by zsimic** [comment]
The test case is here: https://github.com/zsimic/setupmeta/tree/master/tests/scenarios/packaged

It simulates an expanded packaged sdist, and verifies that setupmeta behaves as expected when presented one (see file `expected.txt` there, the test exercises basically setupmeta and verifies it keeps producing that expected output)

**Comment by zsimic** [comment]
@jpic were you able to verify the new version 2.3.2 does indeed fix your issue? (without you having to add anything to MANIFEST.in)

**Comment by jpic** [comment]
I think so, because I still have a MANIFEST.in but just for my own stuff, not for entry_points.ini, classifiers.txt etc anymore !
