### ISSUE TITLE
test_wheel fails in isolated VM

### ISSUE THREAD

**Issue by jayvdb** [zsimic/setupmeta#61]
My bet is that extra flags are needed to tell pip to avoid checking dependencies.
```
[   56s] __________________________________ test_wheel __________________________________
[   56s] 
[   56s] sample_project = '/tmp/tmp75i1zr4p/sample'
[   56s] 
[   56s]     def test_wheel(sample_project):
[   56s]         # Fake existence of a build folder, that should be in .gitignore (but isn't)
[   56s]         # Presence of a new file there should not mark version as dirty
[   56s]         build_folder = os.path.join(sample_project, "build")
[   56s]         os.mkdir(build_folder)
[   56s]         with open(os.path.join(build_folder, "report.txt"), "w") as fh:
[   56s]             fh.write("This is some build report\n")
[   56s]     
[   56s]         dist_folder = os.path.join(sample_project, "dist")
[   56s]     
[   56s] >       assert setupmeta.run_program("pip", "wheel", "--only-binary", ":all:", "-w", "dist", ".") == 0
[   56s] E       assert 1 == 0
[   56s] E         +1
[   56s] E         -0
[   56s] 
[   56s] /home/abuild/rpmbuild/BUILD/setupmeta-2.7.16/tests/test_wheel.py:16: AssertionError
```

**Comment by zsimic** [comment]
Thanks for the report! Would love to know how to reproduce this.
I just committed a change that will ensure that the output is shown when a `run_program()` calls while testing.

Can you rerun and show me the reported output?

**Comment by jayvdb** [comment]
It would be easier for me to fix it.

**Comment by zsimic** [comment]
Do you happen to have output from my last commit?
I need to see the output, as it'll tell me what exactly `pip wheel` is reporting here, not sure what thing is bothering it

**Comment by zsimic** [comment]
This made me realize that `test_wheel` is not needed actually, removing the command that motivated its addition: https://github.com/zsimic/setupmeta/pull/62

`test_wheel` was intended to verify that the command `uber_egg` would work as expected, but that command is not useful to have in setupmeta actually, and wasn't even used by the person requesting it.

So: cleaning up that code: removed both commands `uber_egg` (experiment) and `twine` (was intended to help with publishing, but setup.py is not the right place for that)

**Comment by zsimic** [comment]
I'm not familiar with that RPM for SUSE is intended for, I did read through a bit.
You can now remove `BuildRequires: twine` (after I merge the mentioned PR)

I think you can also remove the following section: 
```
Recommends:     python-pip
Recommends:     python-setuptools_scm
Recommends:     python-twine
Recommends:     python-wheel
```

- `pip` is not needed for setupmeta to work (only setuptools)
- `setuptools_scm` is only mentioned in tests, and is never used/referred-to otherwise
- `twine` was optional before, now completely removed
- `wheel` is not needed, the tests were just indirectly exercising it (because of that old `uber_egg` command)

I'll merge this to master branch today, and release tomorrow morning a new version 2.8.0

**Comment by zsimic** [comment]
One final note: if this is building an RPM with setupmeta, then I think you don't really need it...

`setupmeta` is designed to run as an extension to `setuptools`, the only place where it would be useful to mention is in a `setup.py` like:
```
setup_requires="setupmeta"
```

I don't know if there's any value to `yum install` an RPM that would contain setupmeta... as it would be like inert and do nothing...

**Comment by jayvdb** [comment]
We need setupmeta as a build dependency of other PyPI packages; any that include `setup_requires="setupmeta"` in their setup.py , otherwise they dont build.

Thanks for the notes you have made; I'll update our package after it is released.

**Comment by zsimic** [comment]
2.8.0 released now (sorry, got around to it later than I wanted)

**Comment by jayvdb** [comment]
Great.
